import type { Project } from '../types/project';

export const projects: Project[] = [
  {
    id: 1,
    slug: 'ai-audio-automation',

    title: 'AI Audio Processing & Automation System',

    category: {
      en: 'AI AUTOMATION',
      uk: 'AI-АВТОМАТИЗАЦІЯ',
    },

    description: {
      en: 'An end-to-end AI-powered system that automatically transcribes and analyzes customer calls, extracts structured insights, updates business statistics, and delivers results to a custom web interface.',
      uk: 'Комплексна AI-система, яка автоматично транскрибує та аналізує дзвінки клієнтів, формує структуровані інсайти, оновлює бізнес-статистику та передає результати у власний вебінтерфейс.',
    },

    technologies: [
      'React',
      'TypeScript',
      'Material UI',
      'n8n',
      'AI Agents',
      'OpenAI',
      'Webhooks',
      'Google Sheets',
    ],

    image: {
      desktop: '/images/projects/ai-audio/preview.webp',
      mobile: '/images/projects/ai-audio/preview-mobile.webp',
      alt: {
        en: 'AI Audio Processing and Automation System interface',
        uk: 'Інтерфейс системи AI-обробки та автоматизації аудіо',
      },
    },

    details: {
      year: '2026',

      role: {
        en: 'Full Stack Developer & AI Automation Engineer',
        uk: 'Full Stack Developer & AI Automation Engineer',
      },

      type: {
        en: 'AI Automation System',
        uk: 'AI-система автоматизації',
      },

      overview: {
        en: 'A fully automated AI-powered audio processing platform combining a custom React interface with autonomous n8n workflows. The website communicates with the automation layer through webhooks and displays structured results generated by the AI agent.',
        uk: 'Повністю автоматизована AI-платформа для обробки аудіо, що поєднує власний React-інтерфейс з автономними n8n-воркфлоу. Вебсайт взаємодіє з automation-рівнем через webhooks і відображає структуровані результати, сформовані AI-агентом.',
      },

      challenge: {
        en: 'Managers manually listened to customer calls, analyzed feedback and updated Google Sheets. The process required significant time, produced inconsistent results and could not scale as the number of calls increased.',
        uk: 'Менеджери вручну прослуховували дзвінки клієнтів, аналізували відгуки та оновлювали Google Sheets. Процес займав багато часу, давав нерівномірні результати та погано масштабувався зі збільшенням кількості дзвінків.',
      },

      solution: {
        en: 'I designed an automated pipeline that detects new audio files, sends them for transcription, analyzes the transcript with an AI agent, classifies feedback, extracts business insights, updates statistics and returns structured results to the website and internal tools.',
        uk: 'Я спроєктувала автоматизований pipeline, який знаходить нові аудіофайли, передає їх на транскрипцію, аналізує текст через AI-агента, класифікує feedback, формує бізнес-інсайти, оновлює статистику та повертає структуровані результати у вебсайт і внутрішні інструменти.',
      },

      process: [
        {
          title: {
            en: 'Prompt Design',
            uk: 'Prompt Design',
          },
          description: {
            en: 'Defined evaluation criteria, classification rules, metric extraction logic and a predictable JSON response format.',
            uk: 'Визначила критерії оцінювання, правила класифікації, логіку отримання метрик та передбачуваний JSON-формат відповіді.',
          },
        },
        {
          title: {
            en: 'API Integration',
            uk: 'API Integration',
          },
          description: {
            en: 'Connected transcription services, Google Sheets, website webhooks and custom JavaScript parsing.',
            uk: 'Підключила transcription API, Google Sheets, webhooks вебсайту та кастомний JavaScript parsing.',
          },
        },
        {
          title: {
            en: 'Workflow Architecture',
            uk: 'Workflow Architecture',
          },
          description: {
            en: 'Built autonomous n8n workflows with scheduled triggers, status checks, AI analysis, routing and statistics updates.',
            uk: 'Побудувала автономні n8n-воркфлоу з scheduled triggers, перевіркою статусів, AI-аналізом, routing та автоматичним оновленням статистики.',
          },
        },
      ],

      results: [
        {
          value: '100%',
          label: {
            en: 'Automated call review',
            uk: 'Автоматизація аналізу дзвінків',
          },
        },
        {
          value: '2 min',
          label: {
            en: 'Statistics update cycle',
            uk: 'Цикл оновлення статистики',
          },
        },
        {
          value: 'Seconds',
          label: {
            en: 'Result delivery',
            uk: 'Отримання результатів',
          },
        },
      ],
    },

    links: {
      loom: 'https://www.loom.com/share/7610f20575fe4cdc9bf8b9d39bca1fac',
    },

    featured: true,
  },

  {
    id: 2,
    slug: 'renovation-business',

    title: 'Renovation Business Website',

    category: {
      en: 'COMMERCIAL WEBSITE',
      uk: 'КОМЕРЦІЙНИЙ ВЕБСАЙТ',
    },

    description: {
      en: 'A full-cycle commercial website developed from scratch for a renovation business in Germany.',
      uk: 'Комерційний вебсайт, розроблений з нуля для ремонтного бізнесу в Німеччині.',
    },

    technologies: [
      'React',
      'TypeScript',
      'SEO',
      'GA4',
      'Cloudflare',
      'Web3Forms',
      'IONOS',
    ],

    image: {
      desktop: '/images/projects/renovation/preview.webp',
      mobile: '/images/projects/renovation/preview-mobile.webp',
      alt: {
        en: 'Renovation business website',
        uk: 'Вебсайт ремонтного бізнесу',
      },
    },

    details: {
      year: '2026',

      role: {
        en: 'Full Cycle Developer',
        uk: 'Full Cycle Developer',
      },

      type: {
        en: 'Commercial Website',
        uk: 'Комерційний вебсайт',
      },

      overview: {
        en: 'A complete commercial website designed and developed from scratch for a renovation business in Germany, covering UI development, analytics, SEO, legal compliance, infrastructure and deployment.',
        uk: 'Повноцінний комерційний вебсайт для ремонтного бізнесу в Німеччині, розроблений з нуля — від UI та адаптивної верстки до SEO, аналітики, юридичних вимог, інфраструктури й production deployment.',
      },

      challenge: {
        en: 'The business needed a professional digital presence capable of clearly presenting services, generating customer enquiries and supporting local search visibility.',
        uk: 'Бізнесу був потрібен професійний онлайн-ресурс для презентації послуг, отримання клієнтських заявок і покращення видимості у локальному пошуку.',
      },

      solution: {
        en: 'I handled the complete development lifecycle: responsive frontend implementation, contact flows, analytics, GDPR-compliant cookie management, legal pages, Cloudflare configuration, hosting and production deployment.',
        uk: 'Я реалізувала повний цикл розробки: адаптивний frontend, форми зв’язку, аналітику, GDPR-сумісне керування cookies, юридичні сторінки, Cloudflare, hosting і production deployment.',
      },

      results: [
        {
          value: '100%',
          label: {
            en: 'Full-cycle delivery',
            uk: 'Повний цикл розробки',
          },
        },
        {
          value: 'GDPR',
          label: {
            en: 'Compliant setup',
            uk: 'Сумісність',
          },
        },
        {
          value: 'SEO',
          label: {
            en: 'Optimized structure',
            uk: 'Оптимізована структура',
          },
        },
      ],
    },

    featured: true,
  },

  {
    id: 3,
    slug: 'taskpro',

    title: 'TaskPro',

    category: {
      en: 'FULL-STACK APPLICATION',
      uk: 'FULL-STACK ЗАСТОСУНОК',
    },

    description: {
      en: 'A full-stack task management platform developed by a 10-person team.',
      uk: 'Full-stack платформа для керування завданнями, розроблена командою з 10 розробників.',
    },

    technologies: [
      'React',
      'Redux',
      'Node.js',
      'MongoDB',
      'Cloudinary',
      'Swagger',
    ],

    image: {
      desktop: '/images/projects/taskpro/preview.webp',
      mobile: '/images/projects/taskpro/preview-mobile.webp',
      alt: {
        en: 'TaskPro task management application',
        uk: 'Застосунок TaskPro для керування завданнями',
      },
    },

    details: {
      year: '2024',

      role: {
        en: 'Full Stack Developer',
        uk: 'Full Stack Developer',
      },

      type: {
        en: 'Team Full-Stack Application',
        uk: 'Командний full-stack застосунок',
      },

      team: {
        en: '10 developers • 2-week sprint',
        uk: '10 розробників • 2-тижневий sprint',
      },

      overview: {
        en: 'A collaborative task management application with frontend and backend functionality built by a 10-person development team within a two-week sprint.',
        uk: 'Командний застосунок для керування завданнями з frontend і backend функціональністю, створений командою з 10 розробників протягом двотижневого спринту.',
      },

      solution: {
        en: 'On the frontend I implemented Header functionality and a modal flow for editing and submitting user data. On the backend I worked on Swagger API documentation.',
        uk: 'На frontend я реалізовувала Header та modal flow для редагування й надсилання даних користувача. На backend працювала над Swagger API documentation.',
      },
    },

    links: {
      swagger:
        'https://app.swaggerhub.com/apis/DROGALTSEVA92/Swagger-TaskPro/1.0.0',
    },

    featured: true,
  },

  {
    id: 4,
    slug: 'brushbuddy',

    title: 'BrushBuddy',

    category: {
      en: 'COMMERCIAL PROJECT',
      uk: 'КОМЕРЦІЙНИЙ ПРОЄКТ',
    },

    description: {
      en: 'My first commercial development project delivered by a multidisciplinary product team.',
      uk: 'Мій перший комерційний проєкт, реалізований мультидисциплінарною продуктовою командою.',
    },

    technologies: ['React', 'JavaScript', 'Responsive UI', 'REST API'],

    image: {
      desktop: '/images/projects/brushbuddy/preview.webp',
      mobile: '/images/projects/brushbuddy/preview-mobile.webp',
      alt: {
        en: 'BrushBuddy commercial website',
        uk: 'Комерційний вебсайт BrushBuddy',
      },
    },

    details: {
      year: '2024',

      role: {
        en: 'Frontend Developer',
        uk: 'Frontend Developer',
      },

      type: {
        en: 'Commercial Team Project',
        uk: 'Комерційний командний проєкт',
      },

      team: {
        en: '10 developers • 6 QA • Designer • PM • Team Lead',
        uk: '10 developers • 6 QA • Designer • PM • Team Lead',
      },

      overview: {
        en: 'My first commercial project, delivered within three weeks by a multidisciplinary team consisting of developers, QA engineers, design and project management.',
        uk: 'Мій перший комерційний проєкт, реалізований за три тижні мультидисциплінарною командою розробників, QA, дизайнера та менеджменту.',
      },

      solution: {
        en: 'I implemented the About section, custom manual pagination on the product page and shopping cart functionality.',
        uk: 'Я реалізувала секцію About, кастомну ручну пагінацію на сторінці товарів і функціональність shopping cart.',
      },
    },
  },

  {
    id: 5,
    slug: 'food-boutique',

    title: 'Food Boutique',

    category: {
      en: 'E-COMMERCE',
      uk: 'E-COMMERCE',
    },

    description: {
      en: 'A collaborative e-commerce project developed by a 10-person team during an intensive seven-day sprint.',
      uk: 'Командний e-commerce проєкт, розроблений командою з 10 розробників протягом інтенсивного семиденного спринту.',
    },

    technologies: ['JavaScript', 'HTML', 'CSS', 'REST API', 'Responsive UI'],

    image: {
      desktop: '/images/projects/food-boutique/preview.webp',
      mobile: '/images/projects/food-boutique/preview-mobile.webp',
      alt: {
        en: 'Food Boutique e-commerce website',
        uk: 'E-commerce вебсайт Food Boutique',
      },
    },

    details: {
      year: '2023',

      role: {
        en: 'Frontend Developer',
        uk: 'Frontend Developer',
      },

      type: {
        en: 'Team E-commerce Project',
        uk: 'Командний e-commerce проєкт',
      },

      team: {
        en: '10 developers • 7-day sprint',
        uk: '10 розробників • 7-денний sprint',
      },

      overview: {
        en: 'An intensive team e-commerce project focused on product browsing, reusable interface logic and collaboration within a shared codebase.',
        uk: 'Інтенсивний командний e-commerce проєкт із фокусом на product browsing, перевикористовувану UI-логіку та роботу зі спільною кодовою базою.',
      },

      solution: {
        en: 'I developed the product listing functionality, reusable product card markup and custom pagination logic.',
        uk: 'Я розробляла функціональність списку товарів, reusable markup карток продуктів і кастомну логіку пагінації.',
      },
    },
  },
  {
    id: 6,
    slug: 'aquatrack',

    title: 'AquaTrack',

    category: {
      en: 'FULL-STACK TEAM PROJECT',
      uk: 'FULL-STACK КОМАНДНИЙ ПРОЄКТ',
    },

    description: {
      en: 'A team-based full-stack application focused on water tracking and personal hydration statistics. I contributed to both frontend and backend development, implementing the calendar and statistics interfaces on the frontend and creating Swagger API documentation for the backend.',
      uk: 'Командний full-stack застосунок для трекінгу води та персональної статистики гідратації. Я працювала як із frontend, так і з backend частиною: реалізовувала календар і статистику на frontend та створювала Swagger API documentation для backend.',
    },

    technologies: [
      'React',
      'Redux Toolkit',
      'JavaScript',
      'Node.js',
      'MongoDB',
      'REST API',
      'Swagger',
    ],

    image: {
      desktop: '/images/projects/aquatrack/preview.webp',
      mobile: '/images/projects/aquatrack/preview-mobile.webp',
      alt: {
        en: 'AquaTrack water tracking application',
        uk: 'Застосунок AquaTrack для трекінгу води',
      },
    },

    details: {
      year: '2024',

      role: {
        en: 'Full Stack Developer',
        uk: 'Full Stack Developer',
      },

      type: {
        en: 'Team Full-Stack Application',
        uk: 'Командний full-stack застосунок',
      },

      overview: {
        en: 'AquaTrack is a team-developed water tracking application designed to help users monitor daily hydration, review historical data and analyze personal water consumption statistics through a clear and interactive interface.',
        uk: 'AquaTrack — командний застосунок для трекінгу води, який допомагає користувачам контролювати щоденне споживання, переглядати історію та аналізувати персональну статистику гідратації через зрозумілий інтерактивний інтерфейс.',
      },

      challenge: {
        en: 'The product required a user-friendly way to visualize hydration progress over time while keeping frontend state, historical data and backend API interactions consistent across the application.',
        uk: 'Продукту був потрібен зручний спосіб відображення прогресу гідратації в часі, при цьому frontend state, історичні дані та взаємодія з backend API мали залишатися узгодженими в усьому застосунку.',
      },

      solution: {
        en: 'I worked on the frontend calendar and statistics functionality, helping users navigate hydration history and understand their progress through visual data. On the backend side, I created and maintained Swagger API documentation to make the available endpoints clear and easier to use across the development team.',
        uk: 'На frontend я працювала над функціональністю календаря та статистики, щоб користувачі могли переглядати історію гідратації й аналізувати свій прогрес через візуальні дані. На backend я створювала та підтримувала Swagger API documentation, щоб endpoints були зрозумілими та зручними для використання командою.',
      },

      process: [
        {
          title: {
            en: 'Calendar Interface',
            uk: 'Calendar Interface',
          },
          description: {
            en: 'Implemented calendar-related frontend functionality for navigating and displaying hydration history.',
            uk: 'Реалізовувала frontend-функціональність календаря для навігації та відображення історії споживання води.',
          },
        },
        {
          title: {
            en: 'Statistics',
            uk: 'Statistics',
          },
          description: {
            en: 'Developed statistics-related UI and data presentation to help users understand hydration progress and trends.',
            uk: 'Розробляла UI та відображення статистичних даних, щоб користувачі могли бачити прогрес і тенденції гідратації.',
          },
        },
        {
          title: {
            en: 'API Documentation',
            uk: 'API Documentation',
          },
          description: {
            en: 'Created Swagger documentation for backend endpoints to improve API clarity and collaboration between frontend and backend developers.',
            uk: 'Створювала Swagger documentation для backend endpoints, щоб покращити зрозумілість API та взаємодію між frontend і backend розробниками.',
          },
        },
      ],

      results: [
        {
          value: 'Full Stack',
          label: {
            en: 'Frontend + backend contribution',
            uk: 'Внесок у frontend і backend',
          },
        },
        {
          value: '2',
          label: {
            en: 'Key frontend modules',
            uk: 'Ключові frontend-модулі',
          },
        },
        {
          value: 'Swagger',
          label: {
            en: 'Backend API documentation',
            uk: 'Документація backend API',
          },
        },
      ],
    },

    links: {
      live: 'https://aqua-track-olive.vercel.app/',
      swagger:
        'https://app.swaggerhub.com/apis/DROGALTSEVA92/next-swagger_api_aqua_track/1.0',
    },

    featured: true,
  },
];
